### ISSUE TITLE
Should be Java-based.

### ISSUE THREAD

**Issue by confiteria** [Moudoux/Aristois-Installer#1]
.NET is old and harder to work with. Java is cross-platform and will allow Linux users, like me, to use this as well.

**Comment by Moudoux** [comment]
First of all, it's not Visual Basic nor is it Visual Basic.NET. It's C#.NET. And the reason i made it Windows exclusive is because of Windows users having trouble running jars for some reason (Java not installed, etc).

With some modification to the code, this can be run on Linux as well, as .NET can be ran on Linux nowadays.

Furthermore C# is no harder to code in than Java.

**Comment by confiteria** [comment]
Mono sucks too, and yeah, the new Minecraft launcher installs Java in the background. Understandable. Also, I did mean to put .NET, anything that uses the .NET framework isn't very well supported on Linux.

**Comment by Moudoux** [comment]
My reasoning is that linux users should be able to run a jar file. Some windows users do not know how to do this, running a .exe file is just easier as it requires nothing to be installed. The Minecraft java runtime is not installed system wide.

This installer only downloads the jar installer and executes it with the Minecraft runtime. So there is already an Aristois installer made in Java -> https://github.com/Moudoux/EMC-Installer
